// src/app/App.svelte
<!--
  アプリシェルのクローム部分。

  **本文はここに無い**（ADR-0005 / ADR-0007 / 02.architecture.md §8.1）。
  Svelte が描くのはタイトルバー・ステータスバー・通知バー・Welcome だけで、
  `.mx-preview` の中身は `paint.ts` が直接 DOM に入れる。

  本文の受け皿（`#mx-preview`）は index.html 側にあり、Svelte の管理下に無い。
  だから「本文が読める」までにコンポーネントのマウントを待つ必要がない。
-->
<script lang="ts">
  import { documentStore } from '@/features/document/store.svelte';
  import Welcome from '@/features/workspace/Welcome.svelte';
  import { ja } from '@/i18n/ja';
  import { splitPath } from '@/lib/path';

  import NoticeBar from './NoticeBar.svelte';
  import StatusBar from './StatusBar.svelte';

  const meta = $derived(documentStore.meta);
  const split = $derived(splitPath(meta?.path ?? ''));
</script>

<header class="mx-titlebar">
  <span class="mx-titlebar__name">{meta ? split.name : ja.app.name}</span>
  {#if meta}
    <span class="mx-titlebar__dir">{split.dir}</span>
  {/if}
</header>

{#if documentStore.notice}
  <NoticeBar notice={documentStore.notice} />
{/if}

{#if !meta}
  <Welcome />
{/if}

<StatusBar />

<style>
  /*
   * 行を DOM 順ではなく `grid-area` で明示しているのは、
   * 本文が DOM 上で先に来る（= クロームのマウントを待たずに描ける）ため。
   * grid 本体の定義は shell.css 側にある（本文と共有するレイアウトなので）。
   */
  .mx-titlebar {
    grid-area: 1 / 1;
    display: flex;
    align-items: center;
    gap: var(--mx-space-2);
    padding-inline: var(--mx-space-4);
    border-bottom: 1px solid var(--mx-color-border-subtle);
    background: var(--mx-color-bg-subtle);
    font-size: var(--mx-font-size-ui);
    min-width: 0;
  }

  .mx-titlebar__name {
    font-weight: 600;
    white-space: nowrap;
  }

  .mx-titlebar__dir {
    color: var(--mx-color-fg-subtle);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    min-width: 0;
  }
</style>

// src/app/App.tsx
/**
 * アプリシェルのクローム部分。
 *
 * **本文はここに無い**（ADR-0005 / 02.architecture.md §8.1）。
 * React が描くのはタイトルバー・ステータスバー・通知バー・Welcome だけで、
 * `.mx-preview` の中身は `paint.ts` が直接 DOM に入れる。
 *
 * この構造は S8（React マウントコストが起動時間に占める割合）を
 * 切り分け可能にするためでもある。React を外しても本文は同じ経路で出る
 * （`shell-dom.ts` が同じ DOM を作る）。
 */
import { useDocumentStore } from '@/features/document/store'
import { ja } from '@/i18n/ja'

export function App() {
  const meta = useDocumentStore((s) => s.meta)
  const notice = useDocumentStore((s) => s.notice)
  const stats = useDocumentStore((s) => s.stats)
  const outline = useDocumentStore((s) => s.outline)

  const { dir, name } = splitPath(meta?.path ?? '')

  return (
    <>
      <header className="mx-titlebar">
        <span className="mx-titlebar__name">{meta ? name : ja.app.name}</span>
        {meta ? <span className="mx-titlebar__dir">{dir}</span> : null}
      </header>

      {notice ? (
        <div className={`mx-notice mx-notice--${notice.level}`} role="status">
          {notice.message}
        </div>
      ) : null}

      {meta ? null : (
        <div className="mx-welcome">
          <p className="mx-welcome__title">{ja.welcome.title}</p>
          <p>{ja.welcome.hint}</p>
        </div>
      )}

      <footer className="mx-statusbar">
        {meta ? (
          <>
            <span>{meta.encoding.toUpperCase()}</span>
            <span>{meta.eol.toUpperCase()}</span>
            {meta.bom ? <span>BOM</span> : null}
            <span>{ja.status.bytes(meta.size)}</span>
            {meta.readonly ? <span>{ja.status.readonly}</span> : null}
            {outline.length > 0 ? <span>見出し {outline.length}</span> : null}
          </>
        ) : null}
        <span className="mx-statusbar__spacer" />
        {stats ? <StatusStats stats={stats} /> : null}
      </footer>
    </>
  )
}

function StatusStats({
  stats,
}: {
  stats: NonNullable<ReturnType<typeof useDocumentStore.getState>['stats']>
}) {
  return (
    <>
      <span>
        {stats.site} / {stats.strategy}
        {stats.chunks > 1 ? ` / ${stats.chunks} chunks` : ''}
      </span>
      <span>{ja.status.parsedIn(stats.parseMs)}</span>
      <span>{ja.status.paintedIn(stats.paintMs)}</span>
    </>
  )
}

/** パスをディレクトリとファイル名に割る。Windows と POSIX の両方を受ける。 */
export function splitPath(path: string): { dir: string; name: string } {
  const index = Math.max(path.lastIndexOf('\\'), path.lastIndexOf('/'))
  if (index < 0) return { dir: '', name: path }
  return { dir: path.slice(0, index), name: path.slice(index + 1) }
}
